blog/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.post_list, name='home'),
    re_path(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    #re_path('<int:pk>/', views.post_detail, name='post_detail'),
    #re_path(r'^(?P<slug>\w+)/$', views.post_detail, name='post_detail'),
    re_path(r'^post/new/$', views.post_new, name='post_new'),

    re_path(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

    # re_path('<slug:slug>/', views.post_detail, name='post_detail')


]

panproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('students/', include('students.urls')),
    path('blog', include('blog.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   # New

admin.site.site_header = "POLY-PEDA-BDU Admin"

students/urls.py
from django.urls import path
from . import views

urlpatterns = [

# path('', views.main, name='main'),
path('', views.students, name='students'),
path('details/<int:id>', views.details, name='details'),

path('testing/', views.testing, name='testing'),
path('link1/', views.link1, name='link1'),
path('link2/', views.link2, name='link2'),
path('link3/', views.link3, name='link3'),
path('search/', views.index, name='index'),

]

students/models.py
from django.db import models
import datetime


class Student(models.Model):
    objects = None
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    phone = models.IntegerField(null=True , blank=True)
    #    joined_date = models.DateField(null=True)
    #    FRESHMAN = "FR"
    #    SOPHOMORE = "SO"
    #    JUNIOR = "JR"
    #    SENIOR = "SR"
    #    GRADUATE = "GR"
    #    YEAR_IN_SCHOOL_CHOICES = [
    #        (FRESHMAN, "Freshman"),
    #        (SOPHOMORE, "Sophomore"),
    #        (JUNIOR, "Junior"),
    #        (SENIOR, "Senior"),
    #        (GRADUATE, "Graduate"),
    #    ]
    #    year_in_school = models.CharField(
    #        max_length=2,
    #        choices=YEAR_IN_SCHOOL_CHOICES,
    #        default=FRESHMAN,
    #    )

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Male')
    department = models.CharField(max_length=255, default='')
    COURSE_YEARS_CHOICES = (
        ('2', 'Two Years Course'),
        ('4', 'Four Years Course'),
    )
    no_of_course_years = models.CharField(max_length=10, choices=COURSE_YEARS_CHOICES, default='4')

    YEAR_CHOICES = [(r, r) for r in range(1959, datetime.date.today().year -7)]

    year_of_graduation = models.IntegerField(('Year Of Graduation'), choices=YEAR_CHOICES, default=datetime.datetime.now().year -8)
    INSTITUE_CHOICES = (
        ('POLY', 'Bahr Dar Polytechnic Institute'),
        ('PEDA', 'Bahr Dar Pedagogy'),
        ('BDU', 'Bahr Dar University'),
    )
    graduated_from = models.CharField(max_length=20, choices=INSTITUE_CHOICES, default='BDU')

students/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Student
from django.db.models import Q
from django.shortcuts import render


def students(request):
    mystudents = Student.objects.all().values()
    template = loader.get_template('all_students.html')
    context = {
        'mystudents': mystudents,
    }
    return HttpResponse(template.render(context, request))


def details(request, id):
    mystudent = Student.objects.get(id=id)
    template = loader.get_template('details.html')
    context = {
        'mystudent': mystudent,
    }
    return HttpResponse(template.render(context, request))


def main(request):
    template = loader.get_template('main.html')
    return HttpResponse(template.render())


def testing(request):
    template = loader.get_template('template.html')
    context = {
        'fruits': ['Apple', 'Banana', 'Cherry'],
    }
    return HttpResponse(template.render(context, request))


def link1(request):
    template = loader.get_template('link1.html')
    return HttpResponse(template.render())


def link2(request):
    template = loader.get_template('link2.html')
    return HttpResponse(template.render())


def link3(request):
    template = loader.get_template('link3.html')
    return HttpResponse(template.render())


def index(request):
    if request.method == "GET":
      if 'q' in request.GET:
          q = request.GET['q']
          # data = Data.objects.filter(first_name__icontains=q)
          multiple_q = Q(Q(firstname__icontains=q) | Q(lastname__icontains=q))
          student = Student.objects.filter(multiple_q)
      else:
         student = Student.objects.all()
      context = {
        'student': student,
        'q':q
      }
    # template = loader.get_template('index.html')
    # return HttpResponse(request, template.render(), context)
    return render(request, 'index.html', context)

students/templates/all_students.html
{% extends "master.html" %}

{% block title %}
  POLY-PEDA-BDU Association - List of all members
{% endblock %}


{% block content %}

  <!-- <p><a href="/">HOME</a></p> -->

  <h1>Students</h1>

  <ul>
    {% for x in mystudents %}
      <li><a href="/students/details/{{ x.id }}">{{ x.firstname }} {{ x.lastname }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

students/templates/details.html
{% extends "master.html" %}

{% block title %}
  Details about {{ mystudent.firstname }} {{ mystudent.lastname }}
{% endblock %}


{% block content %}
  <h1>{{ mystudent.firstname }} {{ mystudent.lastname }}</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p>Phone:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.phone }}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p>Gender:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.get_gender_display}}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p>Department:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.department}}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p>Course Years:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.get_no_of_course_years_display}}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <p>Graduation Year:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.year_of_graduation}}</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p>Graduated from:</p>
    </div>
    <div class="col-sm-8">
       <p>{{ mystudent.get_graduated_from_display}}</p>
    </div>
  </div>

</div>

{% endblock %}

students/templates/index.html
{% extends "master.html" %}

{% block title %}
  POLY-PEDA-BDU Association
{% endblock %}


{% block content %}

   {% if q %}
     <h1>You searched For <span style="color:red">"{{q}}"</span>  </h1>
   {% else %}
      <h1>Hey! You forgot To Search For A Student </h1>
   {% endif %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">First</th>
      <th scope="col">Last</th>
    </tr>
  </thead>
  <tbody>
   {% for student in student%}
    <tr>
      <td>{{student.firstname}}</td>
      <td>{{student.lastname}}</td>
      <td>{{student.year_in_school}}</td>
    </tr>
   {% endfor %}
  </tbody>
</table>

{% endblock %}

students/templates/link1.html
{% extends "master.html" %}

{% block title %}
  Details about {{ mymember.firstname }} {{ mymember.lastname }}
{% endblock %}


{% block content %}


  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
      ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
      ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
      sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

students/templates/link2.html
{% extends "master.html" %}

{% block title %}
  Details about {{ mymember.firstname }} {{ mymember.lastname }}
{% endblock %}


{% block content %}


  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
      dolore magna aliqua. Scelerisque varius morbi enim nunc faucibus. Et odio pellentesque diam volutpat commodo sed egestas egestas. Sed vulputate odio ut enim blandit volutpat. Id aliquet lectus proin nibh nisl condimentum id. Mattis nunc sed blandit libero. Urna nunc id cursus metus. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. At ultrices mi tempus imperdiet nulla. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Fringilla ut morbi tincidunt augue interdum velit. Lobortis elementum nibh tellus molestie nunc.

Aliquet eget sit amet tellus. Congue nisi vitae suscipit tellus mauris a. Eget magna fermentum
      iaculis eu non. Sit amet purus gravida quis blandit turpis cursus. Tempor orci eu lobortis
      elementum nibh tellus molestie nunc non. Tempor commodo ullamcorper a lacus vestibulum.
      Congue nisi vitae suscipit tellus. Turpis in eu mi bibendum neque egestas congue quisque.
      Cursus sit amet dictum sit amet justo donec enim diam. Tortor posuere ac ut consequat semper viverra
      nam libero. Nulla porttitor massa id neque aliquam.
      Senectus et netus et malesuada fames ac turpis. Dui ut ornare lectus sit. Elit scelerisque mauris
      pellentesque pulvinar pellentesque habitant morbi tristique. Donec et odio pellentesque diam
      volutpat commodo sed. Cursus risus at ultrices mi tempus imperdiet. Vel quam elementum pulvinar
      etiam non quam lacus suspendisse. Semper viverra nam libero justo. Etiam sit amet nisl purus in.
      Cras tincidunt lobortis feugiat vivamus. Elementum tempus egestas sed sed risus pretium.
      Etiam dignissim diam quis enim lobortis scelerisque. Odio ut enim blandit volutpat.
      Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Posuere urna nec tincidunt
      praesent semper feugiat nibh. Et netus et malesuada fames ac turpis egestas maecenas pharetra.
      Ut porttitor leo a diam sollicitudin tempor id.

Nibh sed pulvinar proin gravida hendrerit lectus. Faucibus scelerisque eleifend donec pretium
      vulputate. Pellentesque elit eget gravida cum sociis natoque penatibus. Tincidunt arcu non
      sodales neque sodales ut etiam sit. Mollis nunc sed id semper risus in hendrerit gravida.
      Nulla malesuada pellentesque elit eget gravida cum sociis. Nulla facilisi etiam dignissim diam
      quis enim lobortis. Lectus quam id leo in vitae turpis massa sed elementum. Volutpat est velit
      egestas dui. Habitant morbi tristique senectus et netus et. In nibh mauris cursus mattis molestie a
      iaculis at erat. Sit amet volutpat consequat mauris nunc. Cursus metus aliquam eleifend mi in nulla.

Erat nam at lectus urna duis convallis convallis. Mollis aliquam ut porttitor leo a diam sollicitudin
      tempor id. Ultricies leo integer malesuada nunc vel risus. Ullamcorper a lacus vestibulum sed
      arcu non. Facilisis mauris sit amet massa. Porta non pulvinar neque laoreet suspendisse interdum.
      Laoreet non curabitur gravida arcu ac tortor dignissim. Varius duis at consectetur lorem donec.
      Nunc scelerisque viverra mauris in aliquam. Auctor urna nunc id cursus metus aliquam eleifend.</p>
{% endblock %}

students/templates/link3.html
{% extends "master.html" %}

{% block title %}
  Details about {{ mymember.firstname }} {{ mymember.lastname }}
{% endblock %}


{% block content %}


  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
      ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
      ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
      sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

students/templates/main.html
{% extends "master.html" %}

{% block title %}
  POLY-PEDA-BDU Association
{% endblock %}


{% block content %}
  <h1>POLY-PEDA-BDU Association</h1>

  <h3>Students</h3>

  <p>Check out all our <a href="students/">students</a></p>

{% endblock %}

students/templates/master.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% load bootstrap_icons %}
  {% load social_widgets %}
</head>
<body>
    <br>
<div class="container">
<header id="top">
    <!-- Static navbar -->
    <div class="navbar-id">
        <div class="container">

            <div class="row">

                <div class="col-xs-12 col-sm-8 col-md-7">
                    <div class="row">

                        <div class="col-xs-12 col-sm-4 col-lg-3">
                        	<div class="image">
                                <img src="/media/pics/bduethiopia.jpg" class="img-fluid" alt="logo">
		                    </div>

                        </div>
                        <div class="col-xs-12 col-sm-8 col-lg-9">
                            <div class="navbar-claim">
                                <h3>POLY-PEDA-BDU Alumni Association</h3>
                            </div>

                       </div>

                    </div>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-5">
                            <div class="navbar-search">

                             <form class="form-inline" role="form" action="{% url 'index' %}" method="get" name="q">
                                 {% csrf_token %}
                                  <div class="input-group">
                                      <input type="text" class="form-control input-sm" name="q" placeholder="Search For Student" aria-label="Search">
                                       <span class="input-group-btn">
                                          <button>Search</button>
                                            <!--<button class="btn btn-default input-sm" type="submit">
                                               <span class="glyphicon glyphicon-search"></span>
                                               {% bs_icon 'search' size='1.5em' %}
                                          </button>-->
                                      </span>
                                  </div>
                              </form>


<!--
        <form class="d-flex" role="search">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
-->
                       </div>
                </div>
            </div>
        </div>
    </div>


</header>


  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/">HOME</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/students/">STUDENTS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/students/link1/">About Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/students/link2/">Contact Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/blog">Blog</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="/admin/">Admin</a>
    </li>

  </ul>

  {% block content %}
  {% endblock %}




</div>
<div class="footer">
    <div class="container bg-info nav-link link-light">
        <div class="row footer-content">
            <div class="col-xs-6 col-md-6">
                <h3>Kontakt</h3>
	<!--  CONTENT ELEMENT, uid:102590/shortcut [begin] -->
		<div class="csc-default">
		<!--  Inclusion of other records (by reference): [begin] -->



	<!--

		BEGIN: Content of extension "tt_address", plugin "tx_ttaddress_pi1"

	-->
	<div class="tx-ttaddress-pi1">

	<div class="vcard">
		<div class="row">
			<div class="col-md-12 col-sm-9">

				<div class="fn">POLY-PEDA-BDU Alumni Association  </div>


					<div class="adr">
						<div class="street-address" itemprop="streetAddress">street-address</div>
						 <span class="postal-code" itemprop="postalCode">postal-code</span>
                        <span class="locality" itemprop="addressLocality">locality</span><br>

					</div>

				<div class="tel phone" item="telephone"><span><i class="fa fa-phone fa-fw fa-margin-right"></i>telephone</span></div>

				<!--<div class="email"><i class="fa fa-envelope-o fa-fw fa-margin-right"></i><a href="#" class="email" item="email">email</a></div> -->

			</div>
		</div>
	</div>



	</div>

	<!-- END: Content of extension "tt_address", plugin "tx_ttaddress_pi1" -->


		<!--  Inclusion of other records (by reference): [end] -->
			</div>
	<!--  CONTENT ELEMENT, uid:102590/shortcut [end] -->
		<!--<ul><li><a href="de/kontakt/">Kontakt</a></li><li><a href="de/no-cache/psi-search/">Suche</a></li><li><a href="de/psi-sitemap/">Sitemap</a></li><li><a href="de/impressum/">Impressum</a></li><li><a href="de/datenschutz/">Datenschutz</a></li><li><a href="de/datenschutz-social-media/">Datenschutz Social Media</a></li></ul>-->
            </div>
            <div class="col-xs-6 col-md-3">
                <h3>Links</h3>
<div class="news-latest-container">
<!-- ---------
    <a href="https://mail.bdu.edu.et/owa" title="">Bahir Dar University Mail service</a>
---------- -->
    <div class="news-latest-item"><a href="https://www.bdu.edu.et" title="">Bahir Dar University</a>
	</div>
<!--
    <div class="news-latest-item"><span class="news-latest-date">09.05.2023</span>&nbsp;| <a href="de/psi-pressevents/releases-archive/artikel/article/psi-erforscht-mit-partnern-im-projekt-idea-das-automatisierte-fahren-in-bus-depots/" title="PSI erforscht mit Partnern im Projekt IDEA das automatisierte Fahren in Bus-Depots">PSI erforscht mit Partnern im Projekt IDEA das automatisierte Fahren in Bus-Depots</a>
	</div>
-->
</div>

            </div>
            <div class="col-md-3 hidden-sm hidden-xs">

            </div>
        </div>
    </div>
</div>
<div class="container text-center p-4  nav-link link-light bg-info">
<!--<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">-->
          © 2023 Copyright:
         <!-- <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a> -->

          <a class="text-reset fw-bold" > POLY-PEDA-BDU Alumni Association </a>
        </div>

</body>
</html>

students/templates/myfirst.html
<!DOCTYPE html>
<html>
<body>

<h1>Hello World!</h1>
<p>Welcome to my first Django project!</p>

</body>
</html>

students/templates/template.html
<!DOCTYPE html>
<html>
<body>

{% for x in fruits %}
  <h1>{{ x }}</h1>
{% endfor %}

<p>In views.py you can see what the fruits variable looks like.</p>

</body>
</html>